apiVersion: apps/v1
kind: Deployment
metadata:
  name: swears-deployment
  labels:
    app.kubernetes.io/name: swears
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: swears
  template:
    metadata:
      labels:
        app.kubernetes.io/name: swears
    spec:
      containers:
        - name: swears
          image: ghcr.io/loghinalexandru/swears:0.6.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 1
              memory: 64Mi
            limits:
              memory: 64Mi
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: swears-svc
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: swears
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
